### ISSUE TITLE
File size insanely big regardless of settings.

### ISSUE THREAD

**Issue by sandikata** [fzwoch/obs-vaapi#31]
Hello.

I've hit an issue when file size is insanely big (500MB for 1 minute) regardless of any settings.

Can you please share any description for all settings of this plugin ? As it's not clear what they're doing at all?

RX6750XT

Regards.

**Comment by fzwoch** [comment]
These properties are dynamically read from the GStreamer runtime and can change with different versions of the runtime. I will not even try to document these changes. 

In general this plugin is more directed to people who know the differences in rate control, buffer models and quantizers.

Since OBS FFMPEG VAAPI now supports texture sharing I see little reason to use this plugin (as it should be faster than this one), unless you know the reason why you want to use it. (but then it is also expected you know what these knobs mean)
